### ISSUE TITLE
Restart of ambassador caused tenants to become "syncing"

### ISSUE THREAD

**Issue by kivanov-macrometa** [Macrometacorp/pyC8#67] opened 2021-04-14 13:15 UTC
## Description

Updating C8 with latest SSL certificates caused Ambassador to restart and break replication for "demo" tenant. 

https://app.circleci.com/pipelines/github/Macrometacorp/C8Operator/13482/workflows/76e4393a-73df-4976-817a-be4286f2ec25/jobs/24662

Ambassador restarted after update
```
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Mon, 12 Apr 2021 15:53:24 +0000
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Mon, 12 Apr 2021 15:52:00 +0000
      Finished:     Mon, 12 Apr 2021 15:53:22 +0000
    Ready:          True
    Restart Count:  6
```

**Comment by martin-macrometa** [comment] 2021-04-19 08:47
Duplicate of https://github.com/Macrometacorp/C8Platform/issues/2546

**Closed by martin-macrometa** 2021-04-19 08:47 UTC
